### PR TITLE
Update WhitePaper.md

### PR DESCRIPTION
**Pull request by nico-liao0918**

### CODE REVIEW

**Review by james-liao0918 — APPROVED** [review]
Approve

**Review by james-liao0918 — DISMISSED** [review]
Approve and Resolved.

**Review by nico-liao0918 — COMMENTED** [review]
Ok

**Review by james-liao0918 — APPROVED** [review]
Approve

**Review by james-liao0918 — APPROVED** [review]
Approve and Resolved.

**Review by james-liao0918 — CHANGES_REQUESTED** [review]
Update and submit.

**Review by james-liao0918 — APPROVED** [review]
OK

**Pull request closed without merging**
